activo: true
especialidades:
- endocrinologia
filtros:
  meses_permitidos:
  - sep
  dias_permitidos:
  - sabado
  - domingo
  - lunes
  sucursales_permitidas:
  - ramos mejia
notificaciones:
  max_por_turno_por_dia: 1
  gmail_sender: fungiabduction@gmail.com
  emails:
  - jonatantesta@msn.com
  telegram_chat_ids: []
test_email: false
