especialidades:
  - endocrinologia

notificaciones:
  max_por_turno_por_dia: 1
  gmail_sender: fungiabduction@gmail.com
  emails:
    - jonatantesta@msn.com
  telegram_chat_ids:
    - "REEMPLAZAR_CON_TU_CHAT_ID"
